experiment_name: stroke_treatment_eval
output_dir: outputs

# 定义需要评测的模型
models:
  <model_name>:
    type: openai # 对应 med_eval_pipeline/models/ 下的文件名 (api_openai.py -> openai)
    model_name: "<model_name>" # 请替换为你要使用的模型名称
    api_key: "YOUR_API_KEY_HERE" # 请替换为你的 API Key
    base_url: "" # 请替换为你的 base_url，例如 "https://api.openai.com/v1"
    max_tokens: 8192
    temperature: 0.1
    max_retry: 3
    timeout: 120

# 定义需要评测的数据集
datasets:
  STROKE:
    gt_path: ["eval_data/latest/filtered_gt_stroke_v0214/stroke_sampled_benchmark_processed_1_gt.jsonl","eval_data/latest/filtered_gt_stroke_v0214/stroke_sampled_benchmark_processed_2_gt.jsonl","eval_data/latest/filtered_gt_stroke_v0214/stroke_sampled_benchmark_processed_3_gt.jsonl","eval_data/latest/filtered_gt_stroke_v0214/stroke_sampled_benchmark_processed_4_gt.jsonl","eval_data/latest/filtered_gt_stroke_v0214/stroke_sampled_benchmark_processed_5_gt.jsonl"]
    graph_def_path: "data/STROKE/stroke_graph.json"
    prompt_template_path: "prompts/thinking_all_task_cite_version_stroke.txt" # 可选
    reference_guideline_name: "Guidelines for the Early Management of Patients With Acute Ischemic Stroke: 2019 Update to the 2018 Guidelines for the Early Management of Acute Ischemic Stroke: A Guideline for Healthcare Professionals From the American Heart Association/American Stroke Association"
    task: "treatment"

# 评测参数
evaluation_params:
  pass_k: 1 # pass@k 的 k 值
  num_workers: 16 # 并行推理/评分的 worker 数量
  skip_inference: false # 是否跳过推理，直接进行评分（用于重新评分）
  save_interval: 10

# 定义需要计算的 Metrics
metrics:
  GraphBasedMetric: {
    use_hard_check_score: false,
    knowledge_calc_method: 'semantic',
    knowledge_db_path: 'data/STROKE/stroke_guidance_output_v2.jsonl',
    knowledge_key: 'original_text',
    model_local_path: 'ckpt/bge-large-zh-v1.5',
    similarity_threshold: 0.8
  }
  treatment_set_score: {}
  Indication_and_contraindication_score: {}
  set_calibration: {}

